/*
 * @description: 根布局
 * @author: Jack Chen @懒人码农
 * @Date: 2025-02-09 22:54:41
 * @LastEditors: Jack Chen
 * @LastEditTime: 2025-02-10 00:06:47
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={` ${geistSans.variable} ${geistMono.variable} antialiased text-white dark:bg-dark-primary`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
